name: IaC Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    name: Scan IaC with Checkov
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Checkov on K8s manifests
        uses: bridgecrewio/checkov-action@master
        with:
          directory: k8s/
          framework: kubernetes
          soft_fail: true
